"""Wwise bank structure checks; fixtures contain generated bytes, no game assets."""
from __future__ import annotations

import hashlib
import struct
import unittest
from types import SimpleNamespace

from astral_party_auto.modkit.audio_bank import (
    _chunks, _media, _read_object, inspect_wem, replace_bank_bytes,
)


def chunk(tag, data):
    return tag + struct.pack("<I", len(data)) + data


def wem(*, frames=48000, rate=48000, channels=2, size=32, codec=0xFFFF, layout=0x3102, loop=None, cue=None):
    fmt = bytearray(66)
    struct.pack_into("<HHI", fmt, 0, codec, channels, rate)
    struct.pack_into("<H", fmt, 16, 48)
    struct.pack_into("<I", fmt, 20, layout)
    struct.pack_into("<I", fmt, 24, frames)
    body = b"WAVE" + chunk(b"fmt ", bytes(fmt)) + chunk(b"hash", b"h" * 16)
    if loop is not None:
        body += chunk(b"smpl", b"\0" * 28 + struct.pack("<II", 1, 0) + struct.pack("<IIIIII", 0, 0, loop[0], loop[1], 0, 0))
    if cue is not None:
        body += chunk(b"cue ", cue)
    body += chunk(b"data", b"a" * size)
    return b"RIFF" + struct.pack("<I", len(body)) + body


def make_bank(*, first=None, second=None, version=145, stream_type=0, prefetch=False, music=False):
    first, second = first or wem(), second or wem(size=40)
    second_offset = (len(first) + 15) // 16 * 16
    index = struct.pack("<III", 101, 0, len(first)) + struct.pack("<III", 202, second_offset, len(second))
    media = first + b"\0" * (second_offset - len(first)) + second
    header = struct.pack("<IIII", version, 123, 0, 16) + b"header-preserve"
    objects = []
    for media_id, size in ((101, len(first)), (202, len(second))):
        source = struct.pack("<IBIIB", 0x40001, stream_type, media_id, size, 2 if prefetch else 0)
        data = struct.pack("<I", media_id + 1000)
        if music:
            data += b"\0" + struct.pack("<I", 1)
        data += source + b"playback-rules-preserve"
        objects.append(bytes([11 if music else 2]) + struct.pack("<I", len(data)) + data)
    hirc = struct.pack("<I", 2) + b"".join(objects)
    return b"".join(chunk(tag, body) for tag, body in ((b"BKHD", header), (b"DIDX", index),
        (b"DATA", media), (b"HIRC", hirc), (b"STID", b"unknown-chunk-preserve")))


def unity_string(value):
    data = value.encode("utf-8")
    result = struct.pack("<I", len(data)) + data
    return result + b"\0" * (-len(result) % 4)


def bank_object(bank):
    prefix = b"\0" * 28 + unity_string("BATTLE") + struct.pack("<I", len(bank))
    data = prefix + bank
    data += b"\0" * (-len(data) % 4)
    data += struct.pack("<I", 16) + hashlib.md5(bank).digest()
    data += unity_string("SFX") + struct.pack("<I", 2) + unity_string("BGM_Battle") + unity_string("Pause")
    return SimpleNamespace(type=SimpleNamespace(name="MonoBehaviour"), get_raw_data=lambda: data, path_id=1)


class AudioBankTests(unittest.TestCase):
    def test_rebuild_changes_only_selected_media_and_source_sizes(self):
        original = make_bank()
        replacement = wem(size=56, frames=96000)
        updated, info = replace_bank_bytes(original, 101, replacement)
        before = dict(_chunks(original))
        after = dict(_chunks(updated))
        self.assertEqual(before[b"BKHD"], after[b"BKHD"])
        self.assertEqual(before[b"STID"], after[b"STID"])
        items, _, _ = _media(updated)
        self.assertTrue(all(m["editable"] for m in items))
        self.assertEqual(info["sha256"], hashlib.sha256(replacement).hexdigest())
        self.assertEqual(items[1]["sha256"], _media(original)[0][1]["sha256"])
        self.assertEqual(after[b"HIRC"].count(b"playback-rules-preserve"), 2)
        self.assertEqual(items[1]["offset"] % 16, 0)

    def test_restoring_one_media_preserves_another_edit(self):
        original = make_bank()
        updated, _ = replace_bank_bytes(original, 101, wem(size=58))
        updated, _ = replace_bank_bytes(updated, 202, wem(size=80))
        restored, _ = replace_bank_bytes(updated, 101, wem())
        self.assertEqual(_media(restored)[0][0]["sha256"], _media(original)[0][0]["sha256"])
        self.assertEqual(_media(restored)[0][1]["sha256"], hashlib.sha256(wem(size=80)).hexdigest())

    def test_mono_rebuild_updates_md5_and_preserves_metadata(self):
        target = _read_object(bank_object(make_bank()))
        updated, _ = replace_bank_bytes(target.bank, 101, wem(size=58))
        obj = bank_object(make_bank())
        raw = target.updated(updated)
        obj.get_raw_data = lambda: raw
        reopened = _read_object(obj)
        self.assertEqual(reopened.bank, updated)
        self.assertEqual(reopened.events, target.events)
        self.assertEqual(reopened.language, "SFX")
        self.assertEqual(reopened.name, "BATTLE")

    def test_mono_rejects_stale_rawdata_hash(self):
        obj = bank_object(make_bank())
        raw = bytearray(obj.get_raw_data())
        raw[raw.index(b"header-preserve")] ^= 1
        obj.get_raw_data = lambda: bytes(raw)
        with self.assertRaisesRegex(ValueError, "校验"):
            _read_object(obj)

    def test_rejects_changed_rate_channels_or_codec(self):
        for candidate in (wem(rate=44100), wem(channels=1), wem(codec=1)):
            with self.subTest(candidate=inspect_wem(candidate)):
                with self.assertRaises(ValueError):
                    replace_bank_bytes(make_bank(), 101, candidate)

    def test_music_requires_same_sample_count_but_not_same_compressed_size(self):
        original = make_bank(music=True)
        with self.assertRaisesRegex(ValueError, "固定时间线"):
            replace_bank_bytes(original, 101, wem(frames=48001))
        _, info = replace_bank_bytes(original, 101, wem(size=56))
        self.assertTrue(info["editable"])

    def test_preserves_channel_layout_loop_points_and_cues(self):
        for candidate in (wem(layout=0x4102), wem(loop=(0, 47999)), wem(cue=b"mark")):
            with self.assertRaises(ValueError):
                replace_bank_bytes(make_bank(), 101, candidate)
        original = make_bank(first=wem(loop=(100, 47999)))
        with self.assertRaisesRegex(ValueError, "循环点"):
            replace_bank_bytes(original, 101, wem(loop=(200, 47999)))
        _, info = replace_bank_bytes(original, 101, wem(loop=(100, 47999), size=60))
        self.assertTrue(info["editable"])

    def test_rejects_loop_outside_audio(self):
        with self.assertRaisesRegex(ValueError, "循环点"):
            inspect_wem(wem(loop=(0, 48000)))

    def test_streamed_prefetched_and_unknown_version_are_readonly(self):
        for settings in ({"stream_type": 2}, {"prefetch": True}, {"version": 150}):
            original = make_bank(**settings)
            self.assertFalse(_media(original)[0][0]["editable"])
            with self.assertRaises(ValueError):
                replace_bank_bytes(original, 101, wem())

    def test_rejects_damaged_riff_and_wrong_expected_digest(self):
        for candidate in (b"not audio", wem()[:-1], wem() + b"extra"):
            with self.assertRaises(ValueError):
                inspect_wem(candidate)
        with self.assertRaisesRegex(ValueError, "已发生变化"):
            replace_bank_bytes(make_bank(), 101, wem(), expected_sha256="wrong")

    def test_rejects_duplicate_and_overlapping_media(self):
        parts = dict(_chunks(make_bank()))
        for index in (struct.pack("<IIIIII", 101, 0, 100, 101, 128, 100),
                      struct.pack("<IIIIII", 101, 0, 160, 202, 100, 120)):
            damaged = b"".join(chunk(tag, index if tag == b"DIDX" else body) for tag, body in parts.items())
            with self.assertRaises(ValueError):
                _media(damaged)


if __name__ == "__main__":
    unittest.main()
