"""星引擎（吉星派对）Mod 工具核心：读取 / 预览 / 替换 / 安装还原 Unity 资源包。

全程只做本地资源文件替换，不注入进程、不碰反篡改。
"""
from .bundles import (
    AA_SUBPATH,
    aa_dir_for_exe,
    bundle_dirs_for_exe,
    bundle_file_map,
    bundle_source_key,
    build_asset_index,
    extract_texture_png,
    hot_update_dir_for_exe,
    iter_bundle_entries,
    load_asset_index,
    read_bundle_textures,
)
from .categories import (
    ADVANCED_IDS,
    ASSET_TYPES,
    all_categories,
    categorize,
    category_desc,
    category_label,
    count_by_category,
    describe_selection,
    filter_by_category,
)
from .dynamic import (
    DYNAMIC_KIND_LABELS,
    SEQUENCE_MIN_FRAMES,
    SequenceGroup,
    classify_text_asset,
    extract_fairygui_dynamic_names,
    find_fairygui_atlas_texture,
    find_sequence_preview_texture,
    sequence_groups_from_names,
    sorted_sequence_names,
    text_asset_bytes,
)
from .export_assets import default_export_name, export_by_type
from .maker import (
    decode_text_asset_raw,
    export_mod_pack,
    find_anim_preview_texture,
    is_readable_text_asset,
    list_text_assets,
    read_text_asset,
    replace_bundle_animation_raw,
    replace_bundle_text,
    replace_bundle_texture,
    replace_bundle_texture_from_bundle,
)
from .manager import ModAnalysis, ModManager
from .migration import (
    BundleMigrationPlan,
    MigrationTexture,
    TextureMigration,
    logical_bundle_name,
    plan_bundle_migration,
    scan_bundle_textures,
)

__all__ = [
    "AA_SUBPATH",
    "aa_dir_for_exe",
    "bundle_dirs_for_exe",
    "bundle_file_map",
    "bundle_source_key",
    "build_asset_index",
    "extract_texture_png",
    "hot_update_dir_for_exe",
    "iter_bundle_entries",
    "load_asset_index",
    "read_bundle_textures",
    "ADVANCED_IDS",
    "ASSET_TYPES",
    "all_categories",
    "categorize",
    "category_desc",
    "category_label",
    "count_by_category",
    "describe_selection",
    "filter_by_category",
    "DYNAMIC_KIND_LABELS",
    "SEQUENCE_MIN_FRAMES",
    "SequenceGroup",
    "classify_text_asset",
    "extract_fairygui_dynamic_names",
    "find_fairygui_atlas_texture",
    "find_sequence_preview_texture",
    "sequence_groups_from_names",
    "sorted_sequence_names",
    "text_asset_bytes",
    "default_export_name",
    "decode_text_asset_raw",
    "export_by_type",
    "export_mod_pack",
    "find_anim_preview_texture",
    "is_readable_text_asset",
    "list_text_assets",
    "read_text_asset",
    "replace_bundle_animation_raw",
    "replace_bundle_text",
    "replace_bundle_texture",
    "replace_bundle_texture_from_bundle",
    "ModAnalysis",
    "ModManager",
    "BundleMigrationPlan",
    "MigrationTexture",
    "TextureMigration",
    "logical_bundle_name",
    "plan_bundle_migration",
    "scan_bundle_textures",
]
